<a href="https://colab.research.google.com/github/dm-fedorov/pandas_basic/blob/master/кейсы%20по%20анализу%20данных/Дискретизация_квантилизация.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory" target="_blank"></a>

In [1]:
import numpy as np
import pandas as pd

Генерируем 10000 случайных чисел:

In [2]:
dist = np.random.normal(size=10000)
dist

array([-1.13018574,  0.54983511,  0.74479688, ..., -0.99622294,
       -1.24822058, -0.45102909])

Выводим среднее и стандартное отклонение:

In [3]:
(dist.mean(), dist.std()) # т.к. распределение нормальное, но mean стремится к 0, а std к 1

(0.006341241065686729, 1.0063951147875838)

Разбиваем на пять одинаковых по размеру групп (выполняем дискретизацию с помощью [pd.cut](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html)):

In [4]:
bins = pd.cut(dist, 5) # по умолчанию интервалы закрываются справа

Получили категориальную переменную:

In [5]:
bins

[(-2.367, -0.775], (-0.775, 0.817], (-0.775, 0.817], (-0.775, 0.817], (-2.367, -0.775], ..., (-0.775, 0.817], (-0.775, 0.817], (-2.367, -0.775], (-2.367, -0.775], (-0.775, 0.817]]
Length: 10000
Categories (5, interval[float64]): [(-3.966, -2.367] < (-2.367, -0.775] < (-0.775, 0.817] < (0.817, 2.409] < (2.409, 4.0]]

Смотрим категории:

In [6]:
bins.categories

IntervalIndex([(-3.966, -2.367], (-2.367, -0.775], (-0.775, 0.817], (0.817, 2.409], (2.409, 4.0]],
              closed='right',
              dtype='interval[float64]')

Свойство .codes показывает, в какой группе (интервале) находится каждый элемент:

In [7]:
bins.codes

array([1, 2, 2, ..., 1, 1, 2], dtype=int8)

Закрываем интервалы слева:

In [8]:
pd.cut(dist, 5, right=False).categories

IntervalIndex([[-3.958, -2.367), [-2.367, -0.775), [-0.775, 0.817), [0.817, 2.409), [2.409, 4.008)],
              closed='left',
              dtype='interval[float64]')

Генерируем 50 значений возраста в диапазоне от 6 до 45:

In [9]:
ages = np.random.randint(6, 45, 50)
ages

array([40, 27, 39, 25, 11, 24, 34, 13, 21, 43, 36,  6, 19, 38, 16, 30, 18,
       18, 24, 28, 15, 33, 29, 28, 40, 22, 36, 21, 42, 23, 44, 40, 25, 31,
       33, 15, 20, 30, 42, 14, 11, 10, 20, 41, 26, 20, 19, 36, 22, 26])

Можем передать массив значений, который будет представлять ширину кажого из интервалов.

Разбиваем на диапазоны и выводим статистику по ним:

In [10]:
ranges = [6, 12, 18, 35, 50]
agebins = pd.cut(ages, ranges)
agebins.describe()

counts  freqs
categories                 
(6.0, 12.0]        3   0.06
(12.0, 18.0]       7   0.14
(18.0, 35.0]      26   0.52
(35.0, 50.0]      13   0.26
NaN                1   0.02

In [11]:
agebins.describe().counts.sum()

50

In [12]:
### что это???

Добавляем имена для групп:

In [13]:
ranges = [6, 12, 18, 35, 50]
labels = ['Youth', 'Young Adult', 'Adult', 'Middle Aged']
agebins = pd.cut(ages, ranges, labels=labels)
agebins.describe()

counts  freqs
categories                
Youth             3   0.06
Young Adult       7   0.14
Adult            26   0.52
Middle Aged      13   0.26
NaN               1   0.02

Можем разбивать на группы с одинаковым количеством элементов.

In [14]:
dist = np.random.normal(size=10000)
dist

array([-0.93035196, -0.50386034,  1.59637221, ..., -0.28656657,
       -0.16236771,  2.17046558])

Разбиваем на квантили 5 групп с одинаковым количеством элементов:

In [15]:
qbin = pd.qcut(dist, 5)
qbin

[(-5.123, -0.823], (-0.823, -0.245], (0.831, 3.736], (0.831, 3.736], (-0.823, -0.245], ..., (0.252, 0.831], (0.831, 3.736], (-0.823, -0.245], (-0.245, 0.252], (0.831, 3.736]]
Length: 10000
Categories (5, interval[float64]): [(-5.123, -0.823] < (-0.823, -0.245] < (-0.245, 0.252] < (0.252, 0.831] < (0.831, 3.736]]

Эта строка выводит диапазоны значений в каждом квантиле:

In [16]:
qbin.describe()

counts  freqs
categories                     
(-5.123, -0.823]    2000    0.2
(-0.823, -0.245]    2000    0.2
(-0.245, 0.252]     2000    0.2
(0.252, 0.831]      2000    0.2
(0.831, 3.736]      2000    0.2

### Дополнительные ссылки:
    
[Binning Data with Pandas qcut and cut](https://pbpython.com/pandas-qcut-cut.html)