<a href="https://colab.research.google.com/github/dm-fedorov/pandas_basic/blob/master/%D0%BA%D0%B5%D0%B9%D1%81%D1%8B%20%D0%BF%D0%BE%20%D0%B0%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D1%83%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85/COVID-19.ipynb"><img align="left" src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open in Colab" title="Open and Execute in Google Colaboratory" target="_blank"></a>

In [2]:
import numpy as np
import pandas as pd

Генерируем 10000 случайных чисел:

In [3]:
dist = np.random.normal(size=10000)
dist

array([ 0.14961098, -1.53978059, -0.04655853, ...,  0.13913996,
       -0.53511644,  0.67895886])

Выводим среднее и стандартное отклонение:

In [19]:
(dist.mean(), dist.std()) # т.к. распределение нормальное, но mean стремится к 0, а std к 1

(-0.016007011486371677, 1.0088154045697302)

Разбиваем на пять одинаковых по размеру групп (выполняем дискретизацию с помощью [pd.cut](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.cut.html)):

In [5]:
bins = pd.cut(dist, 5) # по умолчанию интервалы закрываются справа

[(-0.923, 0.682], (-2.528, -0.923], (-0.923, 0.682], (0.682, 2.288], (-0.923, 0.682], ..., (0.682, 2.288], (-0.923, 0.682], (-0.923, 0.682], (-0.923, 0.682], (-0.923, 0.682]]
Length: 10000
Categories (5, interval[float64]): [(-4.141, -2.528] < (-2.528, -0.923] < (-0.923, 0.682] < (0.682, 2.288] < (2.288, 3.893]]

Получили категориальную переменную:

In [20]:
bins

[(-0.923, 0.682], (-2.528, -0.923], (-0.923, 0.682], (0.682, 2.288], (-0.923, 0.682], ..., (0.682, 2.288], (-0.923, 0.682], (-0.923, 0.682], (-0.923, 0.682], (-0.923, 0.682]]
Length: 10000
Categories (5, interval[float64]): [(-4.141, -2.528] < (-2.528, -0.923] < (-0.923, 0.682] < (0.682, 2.288] < (2.288, 3.893]]

Смотрим категории:

In [6]:
bins.categories

IntervalIndex([(-4.141, -2.528], (-2.528, -0.923], (-0.923, 0.682], (0.682, 2.288], (2.288, 3.893]],
              closed='right',
              dtype='interval[float64]')

Свойство .codes показывает, в какой группе (интервале) находится каждый элемент:

In [7]:
bins.codes

array([2, 1, 2, ..., 2, 2, 2], dtype=int8)

Закрываем интервалы слева:

In [8]:
pd.cut(dist, 5, right=False).categories

IntervalIndex([[-4.133, -2.528), [-2.528, -0.923), [-0.923, 0.682), [0.682, 2.288), [2.288, 3.901)],
              closed='left',
              dtype='interval[float64]')

Генерируем 50 значений возраста в диапазоне от 6 до 45:

In [22]:
ages = np.random.randint(6, 45, 50)
ages

array([11, 38, 20, 43, 12, 12, 17, 30, 22, 32, 18, 37, 23, 26, 21, 21,  9,
       17, 42, 12, 24,  7, 13,  9, 26, 40,  7, 38, 13, 41, 23, 26, 36, 20,
       19,  6, 36, 43, 15, 30, 24, 30, 24, 42, 43,  6, 40, 15,  9, 34])

Можем передать массив значений, который будет представлять ширину кажого из интервалов.

Разбиваем на диапазоны и выводим статистику по ним:

In [31]:
ranges = [6, 12, 18, 35, 50]
agebins = pd.cut(ages, ranges)
agebins.describe()

counts  freqs
categories                 
(6.0, 12.0]        9   0.18
(12.0, 18.0]       7   0.14
(18.0, 35.0]      19   0.38
(35.0, 50.0]      13   0.26
NaN                2   0.04

In [34]:
agebins.describe().counts.sum()

50

In [ ]:
### что это???

Добавляем имена для групп:

In [29]:
ranges = [6, 12, 18, 35, 50]
labels = ['Youth', 'Young Adult', 'Adult', 'Middle Aged']
agebins = pd.cut(ages, ranges, labels=labels)
agebins.describe()

counts  freqs
categories                
Youth             9   0.18
Young Adult       7   0.14
Adult            19   0.38
Middle Aged      13   0.26
NaN               2   0.04

Можем разбивать на группы с одинаковым количеством элементов.

In [16]:
dist = np.random.normal(size=10000)
dist

array([-1.1913734 , -0.23722646,  1.62671277, ..., -1.10004681,
       -2.61670768, -1.02935352])

Разбиваем на квантили 5 групп с одинаковым количеством элементов:

In [17]:
qbin = pd.qcut(dist, 5)
qbin

[(-4.566000000000001, -0.863], (-0.274, 0.24], (0.839, 3.831], (-4.566000000000001, -0.863], (0.24, 0.839], ..., (-0.863, -0.274], (-0.274, 0.24], (-4.566000000000001, -0.863], (-4.566000000000001, -0.863], (-4.566000000000001, -0.863]]
Length: 10000
Categories (5, interval[float64]): [(-4.566000000000001, -0.863] < (-0.863, -0.274] < (-0.274, 0.24] < (0.24, 0.839] < (0.839, 3.831]]

Эта строка выводит диапазоны значений в каждом квантиле:

In [18]:
qbin.describe()

counts  freqs
categories                                 
(-4.566000000000001, -0.863]    2000    0.2
(-0.863, -0.274]                2000    0.2
(-0.274, 0.24]                  2000    0.2
(0.24, 0.839]                   2000    0.2
(0.839, 3.831]                  2000    0.2

### Дополнительные ссылки:
    
[Binning Data with Pandas qcut and cut](https://pbpython.com/pandas-qcut-cut.html)